### ISSUE TITLE
Headers passed to ActiveStorageProvider don't make it to DirectUploadProvider

### ISSUE THREAD

**Issue by CaptainLexington** [cbothner/react-activestorage-provider#22]
I've been passing a `headers` prop to `ActiveStorageProvider`, but the request to `direct_upload` doesn't have those headers. When I put a breakpoint in `addHeaders` in `Upload.js`, `this.options.headers` is `undefined` - but when I put that breakpoint in `ActiveStorageProvider`'s `render` method in `index.js`, `headers` has the correct value when it's destructured on line 51 - it's just not passed down or used anywhere. Is this the desired behavior? The documentation is not clear.

**Comment by cbothner** [comment]
Thanks for opening this issue. You’re right that the documentation isn’t clear on this.

That was the desired behavior, my thinking being that in a standard Rails app the `ActiveStorage::DirectUploadsController` doesn’t expect any custom headers, but that your model’s controllers often will. I don’t feel strongly, however, and I’m open to reconsidering.

Can you provide a little more detail about your use case? Are you using a custom direct uploads controller? What headers are you hoping to pass through?

**Comment by CaptainLexington** [comment]
We're just trying to authenticate with our `direct_uploads` route. I'm not very familiar with ActiveStorage, but the back-end guy tells me that ActiveStorage usually depends on a CSRF token that's embedded when the page is rendered, but since we're using not using Rails for serving our SPA that token isn't available. We want to use our normal authentication token for this, but we're open to other strategies. What do other Rails/React users normally do?

**Comment by cbothner** [comment]
ActiveStorage does depend on the CSRF token, which the `@rails/activestorage` package this library depends on looks for (in a meta tag in the document head) and includes automatically.

Since you’re not using Rails to serve the SPA, I see why you’re looking for another way to authenticate the uploads. I think the approach you’re considering is reasonable, and probably how most in your situation will do it.

I’m going to test with my vanilla ActiveStorage setup just to make sure unnecessary headers won’t cause any problems, then I’ll change this library to pass the headers as you’ve suggested.

**Comment by cbothner** [comment]
Released as v0.8.0

**Comment by CaptainLexington** [comment]
Wow, thank you so much!
