### ISSUE TITLE
Protocol should not default to https when only host is specified

### ISSUE THREAD

**Issue by dsound-zz** [cbothner/react-activestorage-provider#28]
I'm a new React developer and trying to combine a Rails API with ActiveStorage. My model on the backend is User and I would like to be able to attach an avatar in React when updating the user profile. I've placed the given code in the readme and got the functionality working but getting errors on backend. I think it might have something to do with ActiveStorageProvider sending HTTPS instead of HTTP? And also the address defaults to a direct_uploads controller which I did create but wondering if I could just PUT fetch to the Users controller directly? Sorry if this sounds very newb but just trying to create a simple way to post images from React to Rails API.

**Comment by cbothner** [comment]
Hi @dsound-zz. Thanks for your question!

By default, ActiveStorageProvider doesn't assume anything about your protocol. All of its network requests, unless you specify otherwise, are to relative paths—so, the same server and protocol that the page is loading from.

There are two halves to every attachment update.
1. **Upload**: we create an `ActiveStorage::Blob` (a record for the file, by itself) by hitting a built-in `direct_uploads` endpoint and then we upload the attachment to a storage URL returned by it. You don't need to make your own DirectUploadsController unless you've overriding Rails’ default behavior.
2. **Attachment**: this is the part where we talk to your UsersController to attach the previously uploaded file to your user as their avatar. It's the attachment request that you're pointing to `/users/1.json` with the `endpoint` prop to ASP. From the perspective of your controller, the avatar is no different from the user’s name.

If you are seeing any particular error message, please include it. I'll try to help you figure it out.

**Comment by dsound-zz** [comment]
and is there an issue with http vs https?

**Comment by cbothner** [comment]
There shouldn't be. Are you using a different host for your Rails API and for your React app?

**Comment by dsound-zz** [comment]
my Rails app is on localhost 9000 and my React app is on 3000. 

Here's my initial config based on the readme: 

`  <ActiveStorageProvider
    endpoint={{
    path: `/profile`,
    model: 'User',
    host: `localhost:9000`,
    method: 'PUT'
  
    }}`

and then when I try to upload an image, I get this error: 

`index.es.js:1806 OPTIONS https://localhost:9000/rails/active_storage/direct_uploads net::ERR_SSL_PROTOCOL_ERROR
value @ index.es.js:1806
(anonymous) @ index.es.js:1221
value @ index.es.js:1492
(anonymous) @ index.es.js:1481
load (async)
value @ index.es.js:1480
value @ index.es.js:1474
value @ index.es.js:1218
(anonymous) @ index.es.js:1985
start @ index.es.js:1984
(anonymous) @ index.es.js:2149
_callee2$ @ index.es.js:2148
tryCatch @ index.es.js:184
invoke @ index.es.js:403
prototype.(anonymous function) @ index.es.js:237
asyncGeneratorStep @ index.es.js:878
_next @ index.es.js:900
(anonymous) @ index.es.js:907
(anonymous) @ index.es.js:896
_callee$ @ index.es.js:2100
tryCatch @ index.es.js:184
invoke @ index.es.js:403
prototype.(anonymous function) @ index.es.js:237
asyncGeneratorStep @ index.es.js:878
_next @ index.es.js:900
(anonymous) @ index.es.js:907
(anonymous) @ index.es.js:896
(anonymous) @ index.es.js:2111
onChange @ UserProfileContainer.js:113
apply @ _apply.js:20
baseInvoke @ _baseInvoke.js:22
apply @ _apply.js:23
(anonymous) @ _overRest.js:36
(anonymous) @ Input.js:78
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:265
executeDispatch @ react-dom.development.js:571
executeDispatchesInOrder @ react-dom.development.js:596
executeDispatchesAndRelease @ react-dom.development.js:695
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:704
forEachAccumulated @ react-dom.development.js:676
runEventsInBatch @ react-dom.development.js:844
runExtractedEventsInBatch @ react-dom.development.js:852
handleTopLevel @ react-dom.development.js:5030
batchedUpdates$1 @ react-dom.development.js:21425
batchedUpdates @ react-dom.development.js:2247
dispatchEvent @ react-dom.development.js:5110
1:1 Uncaught (in promise) Error creating Blob for "DordmolUYAAYwBs.jpg". Status: 0`

and on the Rails side my error is: 

`2019-03-19 16:55:14 -0400: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
---
2019-03-19 16:55:14 -0400: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

**Comment by cbothner** [comment]
Okay, yeah, I see.

*If* you specify `host` in `endpoint`, then we do currently default to https for the protocol. That is not helpful behavior, and I'll change it to match the protocol of the page.

For now, you should be able to get past this error by changing your endpoint config to
```js
{
  path: '/profile',
  model: 'User',
  attribute: 'avatar',
  method: 'PUT',
  protocol: 'http',
  host: 'localhost',
  port: '9000'
}
```

**Comment by dsound-zz** [comment]
Oh great! This is already getting further for me now. Now I just get a `ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken): ` error in Rails. 
If I want to avoid this path by default and go to /api/v1/users instead, do I declare that in your package in React? Under path?

**Comment by cbothner** [comment]
If you set path to `/api/v1/users` that’ll do it. You can pass your Authorization header to the header prop. `headers={{ Authorization: 'Bearer asdf' }}`

By the way, heads up. Out of the box, ActiveStorage doesn’t play nice as a stateless API. That InvalidAuthenticityToken error you got is because the built in DirectUploadsController is checking for a CSRF (cross-site request forgery) token that Rails embeds in every page it sends to the client. But if you’re hosting your React app on a different server, as opposed to serving it inside a Rails view, you won’t have that CSRF token. Presumably intentional because you’ll be handling authentication some other way.

You’ll need to override DirectUploadsController to disable forgery protection and to enable whatever your JWT check.

```ruby
# /app/controllers/direct_uploads_controller.rb
class DirectUploadsController < ActiveStorage::DirectUploadsController
  skip_before_action :verify_authenticity_token
  before_action :your_jwt_check_here
end
```

And then point the route to your overridden controller

```ruby
# /config/routes.rb
post '/rails/active_storage/direct_uploads', to: 'direct_uploads#create'
```

**Comment by dsound-zz** [comment]
Ok great and thanks for the hand holding on this. I'm still getting a 422 with `Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms)`

I'm not exactly sure what I would put for `before_action` in `/app/controllers/direct_uploads_controller.rb`

I have a method called `curr_user` that checks to see if the current user is the one that matches current token. I tried `before_action current_token` but that didn't help either.

**Comment by cbothner** [comment]
Sure no worries. The symbol there, `:your_jwt_check_here`, has to correspond [to the name of a method on the controller](https://guides.rubyonrails.org/action_controller_overview.html#filters). You can either define one below to do something unique to the controller at hand, or call one defined in a superclass. If you call `render` or `head` in a method used with a before_action hook, it stops the request cycle and doesn’t perform the action.

A common pattern looks like this:

```ruby
class ThingsController < ApplicationController
  before_action :authenticate_user

  def create
    # you have to be signed in to make a thing
```

```ruby
class ApplicationController < ActionController::Base
  def authenticate_user
    head :unauthorized unless user_signed_in?
  end
end
```

Since your DirectUploadsController doesn’t inherit from your ApplicationController, you don’t necessarily have access to your `curr_user` or `current_token` methods unless you include them. Maybe pull that behavior out of ApplicationController and make an `Authenticable` [concern](https://api.rubyonrails.org/classes/ActiveSupport/Concern.html) you can share between the two.


But BTW if you’d rather not roll your own, I've used [Knock](https://github.com/nsarno/knock) for JWT-based authentication and found it pretty nice.

**Comment by dsound-zz** [comment]
Thank you so much for your help. I'll give this a shot a report back. This is a great solution for getting React to play nice with Active Storage.

**Comment by dsound-zz** [comment]
Hi there,
So revisited my app to see if I can get an attachment working in React to store in ActiveRecord in Rails. 
I still cannot get out from under the 422 error: 

```
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms)
```

This makes sense but I'm wondering the the work around since my DirectUploadsController does not inherit from ApplicationController. 

I've tried changing the route of `put "/rails/active_storage/direct_uploads"` to hit `to: users#update`
but this doesn't affect anything. I'm not even sure where to put a byebug to trace everything. Sorry for my newbieness on this but would love to be able to get React to play nice with ActiveStorage. I've just learned implementing JWT so still getting my head wrapped around that as well.

**Comment by dsound-zz** [comment]
Oh and here's what my `DirectUploadsController` looks like right now. I brought in 2 methods from my Users Class just to see if it would hit them:

`class DirectUploadsController < ActiveStorage::DirectUploadsController

  skip_before_action :verify_authenticity_token]
  before_action :token => ENV[:jwt]

  def create
    @user = User.new(
      username: params[:username],
      password: params[:password]
    )
    if @user.save
    encode_token(@user.id)
      render json: {user: UserSerializer.new(@user), token: ENV['jwt']}, status: :ok
    else
      render json: {errors: @user.errors.full_messages}
    end
  end



  def update
   if curr_user.id == @user.id
      @user.update(user_params)
      @user.avatar.attach(params[:user][:avatar])
      if @user.save
      render json: @user, status: :accepted
    else
     render json: { errors: @user.errors.full_messages }, status: :unprocessible_entity
      end
    end

end
`

**Comment by cbothner** [comment]
Okay yeah I see what your problem is. Comes back to that two-step process I mentioned earlier. First we upload, then we attach.

All the files attached to every model in your app live in the same place, undifferentiated. User avatars right next to receipt images. Your user models are connected to their avatar files by these attachments. There might be an attachment that says "user 16's avatar is file 23'. The attachments table (that ActiveStorage comes with) is what's called a "join table".

The DirectUploadsController just makes room for the file in the blobs table. It says "send the file to this url and I'll know it as file 23". That's what it means to create a direct upload. Then we can make a different request to your UsersController and say "the avatar for user 16 is file 23."

So yeah, you don't want to change what the DirectUploadsController does to such a great degree. Really all you want to change about it is the before_action filters. For now, you probably don't need to worry about putting in your own JWT check—you can come back to that. See if you can get it to work with just this:

```ruby
# /app/controllers/direct_uploads_controller.rb
class DirectUploadsController < ActiveStorage::DirectUploadsController
  skip_before_action :verify_authenticity_token

  # the create action is inherited from https://github.com/rails/rails/blob/5-2-stable/activestorage/app/controllers/active_storage/direct_uploads_controller.rb#L7
end

# /config/routes.rb
post '/rails/active_storage/direct_uploads', to: 'direct_uploads#create'
```

And then in your users controller, all you need is something like this

```ruby
# /app/controllers/api/v1/users_controller.rb

def update
  return head :forbidden unless curr_user.id == @user.id

  if @user.update(user_params)
    render json: @user, status: :accepted
  else
    render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
  end
end

def user_params
  # permit :avatar here so it can be included in the @user.update line
  params.require(:user).permit(:name, ..., :avatar)
end
```

**Comment by dsound-zz** [comment]
Ok great and just to be clear, is the create action in that github exampple included in one file under 
`class DirectUploadsController < ActiveStorage::DirectUploadsController` 

or is it a separate file with the first line of code (mine doesn't have `class AvtiveStorage`):

`class ActiveStorage::DirectUploadsController < ActiveStorage::BaseController`

**Comment by cbothner** [comment]
Yeah, so the link I included there isn’t an example for you to copy. That's actually the rails source code, showing you where the `ActiveStorage::DirectUploadsController` that you're inheriting from is defined.

You might already know some of this, but if not: Inheritance is one way we can share code between classes in Ruby. The ` < ActiveStorage::DirectUploadsController` part of your
```ruby
class DirectUploadsController < ActiveStorage::DirectUploadsController
```
line is saying that your DirectUploadsController "inherits from" ActiveStorage'. Every class has all the methods it defines, and also all the methods defined by its parent (the class it inherits from) and all of its parent's parents. [Read more about inheritance here.](https://www.rubyguides.com/2019/01/what-is-inheritance-in-ruby/)

So just like you don't have to write any code to make `.update` work on a User object, you don't need to write any code for the `DirectUploadsController`'s `create` action. By inheriting from `ActiveStorage::DirectUploadsController`, which is internal to Rails, and **not** doing `def create` yourself, you're saying "all of the Rails default behavior is fine here!" Which it is: the only thing you need to change is skipping that before_action forgery protection that'll get in your way.

**Comment by dsound-zz** [comment]
Oh yeah that's very clear, thanks! That code example is what provides all the nice Rails magic.

**Comment by dsound-zz** [comment]
Ok still having no luck and it's probably because I'm missing something.
Just to be sure, here's what I have so far in my DirectUploadsController, Routes and the config in ActiveStorageProvide in React:

```
class DirectUploadsController < ActiveStorage::DirectUploadsController

  skip_before_action :verify_authenticity_token


end
```
```
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update, :destroy]

     resources :animals, only: [:index, :show, :update]
     resources :sightings, only: [:index, :show, :create, :update, :destroy] do
       resources :comments
     end
     resources :comments, only: [:create, :update, :destroy] do
       resources :comments
     end


     post "/rails/active_storage/direct_uploads", to: "direct_uploads#create"
     post "/login", to: "auth#login"
     get "/current_user", to: "auth#get_user_from_token"

   end
   root to: 'sightings#index'
 end

end
```

` ``
 <ActiveStorageProvider
    endpoint={{
    path: '/api/v1/users',
    model: 'User',
    attribute: 'avatar',
    method: 'PUT',
    protocol: 'http',
    host: 'localhost',
    port: '9000',
    headers: {
      "Authorization": localStorage.getItem("token")
    }

  }}


  onSubmit={user => this.setState({ avatar: user.avatar })}
  render={({ handleUpload, uploads, ready }) => (
    <div>
    <Input
    type="file"
    disabled={!ready}
    onChange={e => handleUpload(e.currentTarget.files)}
    />

    {uploads.map(upload => {
      switch (upload.state) {
        case 'waiting':
        return <p key={upload.id}>Waiting to upload {upload.file.name}</p>
        case 'uploading':
        return (
          <p key={upload.id}>
          Uploading {upload.file.name}: {upload.progress}%
          </p>
        )
        case 'error':
        return (
          <p key={upload.id}>
          Error uploading {upload.file.name}: {upload.error}
          </p>
        )
        case 'finished':
        return (
          <p key={upload.id}>Finished uploading {upload.file.name}</p>
        )
      }
    })}
    </div>
  )}
  />
  </>);
}
}
```

**Comment by cbothner** [comment]
Hmm I think in routes.rb you don’t want the direct_uploads line to be inside the api/v1 namespace blocks.

**Comment by dsound-zz** [comment]
Ah yes of course! That definitely got rid of the 422. Now I just need to figure of the CORS issue which I thought would be fine since in Rails, I added '*' to CORS allow access. Looks like this is a frontend issue now because everything takes just fine in Rails.

**Comment by dsound-zz** [comment]
Ok got! You have to adjust CORS permissions at your AWS s3 bucket. Here's a great simple solution for this and for anyone struggling with this:

https://mikerogers.io/2018/11/03/configuring-cors-on-s3-for-activestorage.html

Thank you so much for all your help!

**Comment by dsound-zz** [comment]
I guess my final question would be since this type of Active Storage method seems to bypass or does not need the class controller methods like in User for avatar, how does it know which user to associate the uploaded avatar or image with? I thought I might have to code something like this but it doesn't seem to make a difference: 

`          path: `/api/v1/users/${this.state.user.id}`, `

this is to attach an avatar to a User that already exists via `put` or `patch`.

**Comment by dsound-zz** [comment]
Ugh, I'm also getting this error when I include :avatar or :image in my model Serializer attributes:

```
Module::DelegationError (variant delegated to attachment, but attachment is nil):
  
app/serializers/user_serializer.rb:11:in `avatar'
app/controllers/api/v1/auth_controller.rb:18:in `get_user_from_token'
```

**Comment by cbothner** [comment]
It looks like your upload to S3 is failing, so it isn’t getting to the “attachment” step. Are you sure that your s3 api key, region, bucket name, etc. are correct?

When your upload succeeds then it will matter that you specify the user ID in the url, since your controller will be looking for it.

As for your serializer error, you will have to check first whether there is an avatar attached before trying to get a url for it. That’s the error you see when you try to get the url for avatar you’ve never uploaded one.

**Comment by dsound-zz** [comment]
Ok getting even closer. Got images to upload to my AWS S3 bucket. The only issue now is the default Rails direct_upload address which appears to be `http://locahost:3000`. I get this error:

`index.es.js:2343 PUT http://localhost:3000/api/v1/users 404 (Not Found)`

My rails app is running on localhost:9000 since my React app is on localhost:3000. I the Puma config but this doesn't seem to affect the url_helper for direct_uploads.

**Comment by dsound-zz** [comment]
Hey cbothner, just wondering if you'd around for a quick zoom screen share or even just a text chat? I'm very close to getting this working but still not getting some parameters

**Comment by dsound-zz** [comment]
This is working for me to upload to `direct_uploads` and to AWS s3:
```

        <ActiveStorageProvider
        endpoint={{

          protocol: 'http',
          host: 'localhost',
          port: '9000',
          model: 'User',
          path: `${this.state.user.id}`

        }}
```

How do associate this with the right model on the backend?

**Comment by cbothner** [comment]
Yeah, I could jump on a quick screenshare. Send me a link?

**Comment by dsound-zz** [comment]
thanks

https://us04web.zoom.us/j/831977910
