### ISSUE TITLE
Accept an array of Files in handleUpload

### ISSUE THREAD

**Issue by janklimo** [cbothner/react-activestorage-provider#5]
First of all thank you for this package, it's very helpful!

I ran into a use case where the expected `FileList` [type](https://github.com/cbothner/react-activestorage-provider/blob/373c5fd1ea6e76ea94370199330a34c3041801aa/src/types.js#L22) is too strict to be used together with Polaris' `DropZone` [component](https://polaris.shopify.com/components/actions/drop-zone). Here, the `onDrop` callback accepts `File[]` rather than a `FileList`. Would you consider letting `handleUpdate` accept either a `FileList` or an array of `File`s?

Thanks!

**Comment by cbothner** [comment]
This is something that I have been thinking about, since `FileList` really is a pain to work with outside of `<input type="file">`. When this library was first built, it wasn’t clear what ActiveStorage API was going to be stable, so I replicated specifically the functionality provided by Rails’s UJS. Now we know that the [`DirectUpload`](https://github.com/rails/rails/blob/master/activestorage/app/javascript/activestorage/direct_upload.js) class is public, so I’ve been meaning to rewrite the internals to use that. That would allow us to accept `File[]` too.

Thanks for the push. I’ll try to make time for it.
